# Generated by Django 5.2.6 on 2025-09-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_bill_created_by_alter_bill_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
